name: superapp
# A brief description of the app. This description is shown when publishing the package.
description: Elegant and accessible school super app built with Flutter and Supabase. This project provides a modern UI with improved color contrast and typography for a pleasant and inclusive user experience.
publish_to: 'none'
version: 1.0.0+1

# Dart SDK constraints. Adjust the range to match your local Flutter SDK version.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.6
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  # Uncomment if you plan to use SVG assets in the future
  # flutter_svg: ^2.0.10+1
  supabase_flutter: ^2.6.0
  mobile_scanner: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # If you add image or icon assets, list them here
  # assets:
  #   - assets/illustrations/
  #   - assets/icons/
